Repository d2iq-labs/avm, pull requests merged in 2022-12, with the labels that each got.

#6 chore: add license
  LICENSE
Labels: size/L, ignore-for-release

#7 feat: create initial cmd structure
  cmd/initialize/intialize.go
  cmd/root.go
  go.mod
  go.sum
  main.go
Labels: read-for-review

#8 feat: download asdf to source directory
  cmd/initialize/intialize.go
  pkg/sources/asdf/asdf.go
Labels: feature, read-for-review, size/M

#10 feat: add simple cli interface
  cmd/plugin/plugin.go
  cmd/root.go
  cmd/source/source.go
Labels: size/L, feature

#11 refactor: extract init to simple lib interface
  pkg/avm/avm.go
  pkg/avm/doc.go
Labels: size/M

#12 refactor: add simple source interface
  pkg/avm/avm.go
  pkg/sources/asdf/asdf.go
  pkg/sources/asdf/bin/entrypoint.sh
  pkg/sources/asdf/cmd.go
  pkg/sources/asdf/source.go
  pkg/sources/sources.go
Labels: size/L

#13 fix: resolve rebase errors
  cmd/initialize/intialize.go
  cmd/source/source.go
Labels: size/M, fix

#14 refactor: print list of installed plugins
  cmd/source/source.go
  pkg/avm/avm.go
Labels: size/S

#15 feat: use magefile sh to execute local commands
  go.mod
  go.sum
  pkg/sources/asdf/cmd.go
  pkg/sources/asdf/source.go
Labels: feature, size/M
